#!/bin/bash -xe
exec 2>&1

mkdir -p {{pkg.svc_path}}/data/init.groovy.d
cp -r {{pkg.svc_config_path}}/*.groovy {{pkg.svc_data_path}}/init.groovy.d/
cp -r {{pkg.svc_config_path}}/*.xml {{pkg.svc_data_path}}/
cp -r {{pkg.path}}/plugins {{pkg.svc_data_path}}/
