[jenkins]
prefix = "/"
jenkins_admin_username = "admin"
jenkins_admin_password = "password"
admin_email = "root@localhost"
url = "localhost"
NumExecutors = "5"
slavePort = "0"
disableSignup = true

[jenkins.session]
timeout = 60

[jenkins.http]
enabled = true
port = 8080

[jenkins.https]
enabled = false
port = 443

[jenkins.http2]
enabled = false
port = 80

[jenkins.ajp13]
enabled = false
port = 8009

[java]
opts = "-Xms1024M -Xmx2048M -Dfile.encoding=UTF-8 "
